import React from "react"
import { IconButton } from "./icon-button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  IconButton,
  "https://www.figma.com/design/7gFdOSsbUxcHxyp84Ql45Z/%F0%9F%8C%90-OPL-Components-Beta?node-id=80%3A2503",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("state", {
        disabled: true,
      }),
      size: figma.enum("size", {
        small: "sm",
        default: "default",
      }),
      // No matching props could be found for these Figma properties:
      // "icon": figma.instance('icon'),
      // "type": figma.enum('type', {
      //   "primary": "primary",
      //   "secondary": "secondary",
      //   "tertiary": "tertiary"
      // }),
      // "severity": figma.enum('severity', {
      //   "default": "default",
      //   "danger": "danger",
      //   "accent": "accent",
      //   "success": "success"
      // })
    },
    example: (props) => (
      <IconButton disabled={props.disabled} size={props.size} />
    ),
  },
)
