import React from "react"
import { Badge } from "./badge"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Badge,
  "https://www.figma.com/design/7gFdOSsbUxcHxyp84Ql45Z/%F0%9F%8C%90-OPL-Components-Beta?node-id=117%3A63",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "label": figma.string('label'),
      // "type": figma.enum('type', {
      //   "danger": "danger",
      //   "accent": "accent",
      //   "default": "default"
      // }),
      // "size": figma.enum('size', {
      //   "large": "large",
      //   "default": "default"
      // })
    },
    example: (props) => <Badge />,
  },
)
