import React from "react"
import { Avatar } from "./avatar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Avatar,
  "https://www.figma.com/design/7gFdOSsbUxcHxyp84Ql45Z/%F0%9F%8C%90-OPL-Components-Beta?node-id=104%3A13",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "initials": figma.string('initials'),
      // "status": figma.boolean('status'),
      // "icon": figma.instance('icon'),
      // "size": figma.enum('size', {
      //   "20x20": "20x20",
      //   "24x24": "24x24",
      //   "32x32": "32x32",
      //   "48x48": "48x48",
      //   "64x64": "64x64"
      // }),
      // "type": figma.enum('type', {
      //   "initial": "initial",
      //   "icon": "icon",
      //   "image": "image"
      // })
    },
    example: (props) => <Avatar />,
  },
)
